GEEZARD = {"id": "0101", "name": "Geezard", "element": None, "t_value": 1, "r_value": 4, "b_value": 1, "l_value": 5}
FUNGUAR = {"id": "0102", "name": "Funguar", "element": None, "t_value": 5, "r_value": 1, "b_value": 1, "l_value": 3}
BITE_BUG = {"id": "0103", "name": "Bite Bug", "element": None, "t_value": 1, "r_value": 3, "b_value": 3, "l_value": 5}
RED_BAT = {"id": "0104", "name": "Red Bat", "element": None, "t_value": 6, "r_value": 1, "b_value": 1, "l_value": 2}
BLOBRA = {"id": "0105", "name": "Blobra", "element": None, "t_value": 2, "r_value": 3, "b_value": 1, "l_value": 5}
GAYLA = {"id": "0106", "name": "Gayla", "element": "Thunder", "t_value": 2, "r_value": 1, "b_value": 4, "l_value": 4}
GESPER = {"id": "0107", "name": "Gesper", "element": None, "t_value": 1, "r_value": 5, "b_value": 4, "l_value": 1}
FASTITOCALON_F = {"id": "0108", "name": "Fastitocalon-F", "element": "Earth", "t_value": 3, "r_value": 5, "b_value": 2, "l_value": 1}
BLOOD_SOUL = {"id": "0109", "name": "Blood Soul", "element": None, "t_value": 2, "r_value": 1, "b_value": 6, "l_value": 1}
CATERCHIPILLAR = {"id": "0110", "name": "Caterchipillar", "element": None, "t_value": 4, "r_value": 2, "b_value": 4, "l_value": 3}
COCKATRICE = {"id": "0111", "name": "Cockatrice", "element": "Thunder", "t_value": 2, "r_value": 1, "b_value": 2, "l_value": 6}
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": },
# {"id": "", "name": "", "element": "", "t_value": , "r_value": , "b_value": , "l_value": }

CARDS = [
    GEEZARD,
    FUNGUAR,
    BITE_BUG,
    RED_BAT,
    BLOBRA,
    GAYLA,
    GESPER,
    FASTITOCALON_F,
    BLOOD_SOUL,
    CATERCHIPILLAR,
    COCKATRICE
]
